import { User, TestResult, Chapter, LTIData, Subject } from '../types';

export const mockUser: User = {
  id: '1',
  name: 'Alex',
  email: 'alex@example.com',
  examType: 'JEE',
  xp: 1500,
  level: 5,
  streak: 7,
  rank: 142,
  stressIndex: 35,
  optimalLearningState: {
    focus: 78,
    timeOfDay: 'Mid-Morning',
  },
};

export const mockChapters: Record<Subject, Chapter[]> = {
  Math: [
    {
      id: 'm1',
      name: 'Calculus - Limits',
      subject: 'Math',
      proficiency: 82,
      efficiency: 75,
      ltiPotential: 'High',
      needsAttention: null,
    },
    {
      id: 'm2',
      name: 'Algebra - Quadratic Equations',
      subject: 'Math',
      proficiency: 65,
      efficiency: 80,
      ltiPotential: 'Medium',
      needsAttention: 'proficiency',
    },
    {
      id: 'm3',
      name: 'Trigonometry - Identities',
      subject: 'Math',
      proficiency: 88,
      efficiency: 60,
      ltiPotential: 'Low',
      needsAttention: 'efficiency',
    },
  ],
  Physics: [
    {
      id: 'p1',
      name: 'Mechanics - Kinematics',
      subject: 'Physics',
      proficiency: 78,
      efficiency: 85,
      ltiPotential: 'High',
      needsAttention: 'lti',
    },
    {
      id: 'p2',
      name: 'Electrostatics',
      subject: 'Physics',
      proficiency: 55,
      efficiency: 65,
      ltiPotential: 'Medium',
      needsAttention: 'proficiency',
    },
    {
      id: 'p3',
      name: 'Optics - Ray Optics',
      subject: 'Physics',
      proficiency: 90,
      efficiency: 88,
      ltiPotential: 'High',
      needsAttention: null,
    },
  ],
  Chemistry: [
    {
      id: 'c1',
      name: 'Organic - Reactions',
      subject: 'Chemistry',
      proficiency: 72,
      efficiency: 70,
      ltiPotential: 'Medium',
      needsAttention: null,
    },
    {
      id: 'c2',
      name: 'Inorganic - Periodic Table',
      subject: 'Chemistry',
      proficiency: 85,
      efficiency: 75,
      ltiPotential: 'Low',
      needsAttention: null,
    },
    {
      id: 'c3',
      name: 'Physical - Thermodynamics',
      subject: 'Chemistry',
      proficiency: 68,
      efficiency: 82,
      ltiPotential: 'High',
      needsAttention: 'proficiency',
    },
  ],
  Biology: [
    {
      id: 'b1',
      name: 'Cell Biology',
      subject: 'Biology',
      proficiency: 80,
      efficiency: 78,
      ltiPotential: 'Medium',
      needsAttention: null,
    },
    {
      id: 'b2',
      name: 'Genetics - Mendelian',
      subject: 'Biology',
      proficiency: 75,
      efficiency: 70,
      ltiPotential: 'High',
      needsAttention: 'lti',
    },
    {
      id: 'b3',
      name: 'Human Physiology',
      subject: 'Biology',
      proficiency: 88,
      efficiency: 85,
      ltiPotential: 'Medium',
      needsAttention: null,
    },
  ],
};

export const mockTestResults: TestResult[] = [
  {
    id: 't1',
    subject: 'Physics',
    level: 'Mains',
    chapter: 'Mechanics - Kinematics',
    date: '2024-04-28',
    score: 86,
    attempted: 28,
    unattempted: 2,
    correct: 24,
    wrong: 4,
    efficiency: 86,
    cognitiveLoadIndex: 'Moderate',
    lti: 72,
    attempts: [],
    emotionalTimeline: [
      { questionNumber: 1, state: 'Focus', intensity: 85 },
      { questionNumber: 5, state: 'Focus', intensity: 80 },
      { questionNumber: 10, state: 'Stress', intensity: 65 },
      { questionNumber: 15, state: 'Confusion', intensity: 55 },
      { questionNumber: 20, state: 'Focus', intensity: 75 },
      { questionNumber: 25, state: 'Focus', intensity: 82 },
      { questionNumber: 30, state: 'Stress', intensity: 60 },
    ],
    strategyBreakdown: {
      efficient: 70,
      trialAndError: 20,
      guessing: 10,
    },
    comparedToMajority: [
      { questionId: 'q3', studentGotWrong: true, majorityGotRight: true },
      { questionId: 'q7', studentGotWrong: true, majorityGotRight: true },
      { questionId: 'q12', studentGotWrong: true, majorityGotRight: false },
      { questionId: 'q18', studentGotWrong: true, majorityGotRight: true },
    ],
  },
  {
    id: 't2',
    subject: 'Math',
    level: 'Advanced',
    chapter: 'Calculus - Limits',
    date: '2024-04-25',
    score: 78,
    attempted: 25,
    unattempted: 5,
    correct: 19,
    wrong: 6,
    efficiency: 75,
    cognitiveLoadIndex: 'High',
    lti: 68,
    attempts: [],
    emotionalTimeline: [
      { questionNumber: 1, state: 'Focus', intensity: 90 },
      { questionNumber: 5, state: 'Stress', intensity: 70 },
      { questionNumber: 10, state: 'Confusion', intensity: 50 },
      { questionNumber: 15, state: 'Stress', intensity: 60 },
      { questionNumber: 20, state: 'Focus', intensity: 75 },
      { questionNumber: 25, state: 'Focus', intensity: 80 },
      { questionNumber: 30, state: 'Boredom', intensity: 65 },
    ],
    strategyBreakdown: {
      efficient: 60,
      trialAndError: 30,
      guessing: 10,
    },
    comparedToMajority: [
      { questionId: 'q2', studentGotWrong: true, majorityGotRight: true },
      { questionId: 'q5', studentGotWrong: true, majorityGotRight: true },
      { questionId: 'q9', studentGotWrong: true, majorityGotRight: true },
      { questionId: 'q14', studentGotWrong: true, majorityGotRight: false },
      { questionId: 'q21', studentGotWrong: true, majorityGotRight: true },
      { questionId: 'q28', studentGotWrong: true, majorityGotRight: true },
    ],
  },
  {
    id: 't3',
    subject: 'Chemistry',
    level: 'Mains',
    chapter: 'Organic - Reactions',
    date: '2024-04-22',
    score: 92,
    attempted: 30,
    unattempted: 0,
    correct: 28,
    wrong: 2,
    efficiency: 90,
    cognitiveLoadIndex: 'Low',
    lti: 85,
    attempts: [],
    emotionalTimeline: [
      { questionNumber: 1, state: 'Focus', intensity: 88 },
      { questionNumber: 5, state: 'Focus', intensity: 90 },
      { questionNumber: 10, state: 'Focus', intensity: 85 },
      { questionNumber: 15, state: 'Focus', intensity: 92 },
      { questionNumber: 20, state: 'Stress', intensity: 70 },
      { questionNumber: 25, state: 'Focus', intensity: 88 },
      { questionNumber: 30, state: 'Focus', intensity: 90 },
    ],
    strategyBreakdown: {
      efficient: 85,
      trialAndError: 10,
      guessing: 5,
    },
    comparedToMajority: [
      { questionId: 'q15', studentGotWrong: true, majorityGotRight: true },
      { questionId: 'q22', studentGotWrong: true, majorityGotRight: false },
    ],
  },
];

export const mockLTIData: LTIData[] = [
  {
    concept: 'Kinematics',
    applications: ['Projectile Motion', 'Circular Motion', 'Relative Velocity'],
    score: 72,
  },
  {
    concept: 'Thermodynamics',
    applications: ['Heat Engines', 'Refrigerators', 'Phase Transitions'],
    score: 85,
  },
  {
    concept: 'Quadratic Equations',
    applications: ['Optimization Problems', 'Trajectory Analysis', 'Economics Models'],
    score: 65,
  },
];

export const weeklyStressData = [
  { day: 'Mon', stress: 25 },
  { day: 'Tue', stress: 30 },
  { day: 'Wed', stress: 45 },
  { day: 'Thu', stress: 35 },
  { day: 'Fri', stress: 50 },
  { day: 'Sat', stress: 20 },
  { day: 'Sun', stress: 15 },
];

export const overallProgressData = [
  { month: 'Jan', accuracy: 65 },
  { month: 'Feb', accuracy: 68 },
  { month: 'Mar', accuracy: 72 },
  { month: 'Apr', accuracy: 78 },
  { month: 'May', accuracy: 82 },
];

export const subjectWiseAccuracy = {
  Math: 78,
  Physics: 82,
  Chemistry: 85,
  Biology: 80,
};

export const achievements = [
  { id: 1, title: 'Focus Wizard', description: 'Maintained 80%+ focus for 5 consecutive tests', icon: '🧙‍♂️', unlocked: true },
  { id: 2, title: 'Transfer Master', description: 'Achieved LTI > 80 in 3 different topics', icon: '🎯', unlocked: true },
  { id: 3, title: 'Streak Champion', description: '7-day learning streak', icon: '🔥', unlocked: true },
  { id: 4, title: 'Efficiency Expert', description: 'Maintain 85%+ efficiency for a week', icon: '⚡', unlocked: false },
  { id: 5, title: 'Speed Demon', description: 'Complete a test in 50% of allotted time with 90%+ accuracy', icon: '🚀', unlocked: false },
];
